# Change these first
owner: ProFinn24 # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: F1nn.net
    url: https://f1nn.net
  - name: ProShisha24
    url: https://proshisha24.de
  - name: Hiroshima.fun
    url: https://hiroshima.fun

status-website:
  theme: dark
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.f1nn.net
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: status.f1nn.net
  introTitle: "**Status Page**"
  introMessage: 
  navbar:
    - title: Home
      href: https://f1nn.net
    - title: Furret
      href: https://f1nn.net/furret
i18n:
  footer: Page powered by F1nn & ProShisha24
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
